/*
 * Info.java
 *
 * Created on __DATE__, __TIME__
 */

package info;

import Student.Student;

/**
 *
 * @author  __USER__
 */
public class Info extends javax.swing.JFrame {

	/** Creates new form Info */
	public Info(Student s) {
		initComponents(s);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents(final Student s) {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().setLayout(
				new org.netbeans.lib.awtextra.AbsoluteLayout());

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);
		jTextArea1.setText("�˺ţ�"+s.getName()+"\r\n���룺"+s.getPwd()+"\r\n");
		getContentPane().add(
				jScrollPane1,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400,
						300));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	// End of variables declaration//GEN-END:variables

}