/*
 * Main.java
 *
 * Created on __DATE__, __TIME__
 */

package login;

import info.Info;

import java.util.Random;

import javax.swing.JOptionPane;

import Student.Student;
import 界面.Registered;

import db.DB;

/**
 *
 * @author  __USER__
 */
public class Login extends javax.swing.JFrame {

	/** Creates new form Main */
	public Login() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jPasswordField1 = new javax.swing.JPasswordField();
		jLabel3 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().setLayout(
				new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel1.setText("用户名：");
		getContentPane().add(
				jLabel1,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1,
						-1));

		getContentPane().add(
				jTextField1,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 210,
						-1));

		jLabel2.setText("密码：");
		getContentPane().add(
				jLabel2,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1,
						-1));

		getContentPane().add(
				jPasswordField1,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120,
						210, -1));

		jLabel3.setText("验证码：");
		getContentPane().add(
				jLabel3,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1,
						-1));

		getContentPane().add(
				jTextField2,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160,
						130, -1));

		suijishu = getFourRandom();
		jLabel4.setText(suijishu);
		getContentPane().add(
				jLabel4,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 70,
						-1));

		jButton1.setText("登录");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		getContentPane().add(
				jButton1,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1,
						-1));

		jButton2.setText("注册");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		getContentPane().add(
				jButton2,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1,
						-1));

		jButton3.setText("更换");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		getContentPane().add(
				jButton3,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 70,
						-1));

		this.setTitle("用户登录");
		this.setSize(420,350);
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		suijishu = getFourRandom();
		jLabel4.setText(suijishu);
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		new Registered().setVisible(true);
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		String name = jTextField1.getText();
		String pwd = jPasswordField1.getText();
		String sjs = jTextField2.getText();
		if (name == null || name.equals(""))
		{
			JOptionPane.showMessageDialog(null,"用户名不能为空！");
			return;
		}
		
		if (pwd == null || pwd.equals(""))
		{
			JOptionPane.showMessageDialog(null,"密码不能为空！");
			return;
		}
		
		if (sjs == null || sjs.equals(""))
		{
			JOptionPane.showMessageDialog(null,"验证码不能为空！");
			return;
		}
		
		if (suijishu.equals(sjs))
		{
                    SQLmanager.Identification
			Student stu = db.login(name, pwd);
			if (stu != null)
			{
				new Info(stu).setVisible(true);
			}else
			{
				JOptionPane.showMessageDialog(null,"用户名或密码错误！");
				return;
			}
		}else
		{
			JOptionPane.showMessageDialog(null,"登录成功！");
			return;
		}
		
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Login().setVisible(true);
			}
		});
	}
	
	
	public String getFourRandom(){
        Random random = new Random();
        String fourRandom = random.nextInt(10000) + "";
        int randLength = fourRandom.length();
        if(randLength<4){
          for(int i=1; i<=4-randLength; i++)
              fourRandom = "0" + fourRandom  ;
      }
        return fourRandom;
    } 

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private static String suijishu = "";
	DB db = DB.getDB();
	// End of variables declaration//GEN-END:variables

}